---
- name: Check if Xcode already exists
  stat:
    path: "/Applications/Xcode.app"
  register: Xcodeapp

- name: Copy Xcode.xip if not installed
  copy:
    src: "Xcode_{{xcode_version}}.xip"
    dest: "/Users/cbtadmin/Xcode.xip"
  when: not Xcodeapp.stat.exists && xcode_prefix is not defined

- name: Download .xip if prefix
  copy:
    src: "{{ xcode_prefix }}/Xcode_{{xcode_version}}.xip"
    dest: "/Users/cbtadmin/Xcode.xip"
  when: not Xcodeapp.stat.exists && xcode_prefix is defined

- name: Check if Xcode is already extracted
  stat:
    path: "/Users/cbtadmin/Xcode.app"
  register: xcode_extracted
  when: not Xcodeapp.stat.exists

- name: Extract Xcode
  command: xip -x Xcode.xip
  args:
    chdir: "/Users/cbtadmin"
  when: not Xcodeapp.stat.exists and not xcode_extracted.stat.exists

- name: Move Xcode.app
  command: mv Xcode.app /Applications
  args:
    chdir: "/Users/cbtadmin"
  when: not Xcodeapp.stat.exists

- name: remove quarantine xattr
  command: xattr -d com.apple.quarantine Xcode.app
  args:
    chdir: /Applications
  become: yes
  ignore_errors: yes

- name: Accept license (optional)
  shell: xcodebuild -license accept
  become: yes
  when: xcode_accept_license
